### ISSUE TITLE
rm for deleting?

### ISSUE THREAD

**Issue by vasanthaganeshk** [you-dont-need/You-Dont-Need-GUI#10]
We can use rm for permanent delete, for the noobs it might give an idea that it goes in to recycle bin, some clarification might be needed there.

**Comment by stevemao** [comment]
PR welcome :)

**Comment by stevemao** [comment]
PS: I know there's an npm module `trash` that does it. But it's not available for a new machine.

**Comment by vasanthaganeshk** [comment]
[trash-cli](https://github.com/andreafrancia/trash-cli/), [rmtrash](http://www.nightproductions.net/cli.htm) (for osx) seems like an option, otherwise you could add a sentence saying that rm is equivalent to shift-del (permanent delete).

**Comment by stevemao** [comment]
> otherwise you could add a sentence saying that `rm` is equivalent to shift-del (permanent delete).

I think this change sounds reasonable.
@vasanthaganeshk PR welcome :)

**Comment by stevemao** [comment]
note: https://github.com/you-dont-need/You-Dont-Need-GUI/pull/19 is merged. But i'd still change the wording `STOP RIGHT CLICK AND DELETE FILE OR DRAG IT TO RECYCLE` to something like `STOP RIGHT CLICK AND DELETE FILE PERMANENTLY`. Thoughts? cc @dennisboys

**Comment by dennisboys** [comment]
Agree. That's much more concise and to-the-point. 

On a side note, grammatically we are missing a preposition here. STOP RIGHT CLICK AND DELETE _**A**_ FILE PERMANENTLY

I can spot this issue in quite a few places.

STOP RIGHT CLICK AND DUPLICATE _**A**_ FILE
STOP RIGHT CLICK AND DUPLICATE _**A**_ FOLDER

Don't mean to be fussy but just want to keep it grammatically consistent throughout the page. (Ok... fun fact, I have an editor background and will get mad for a misplaced or missed punctuation mark.)

Do you need me to go through the page and correct them? Or it doesn't matter. @stevemao

**Comment by stevemao** [comment]
@dennisboys PR welcome :)

**Comment by stevemao** [comment]
Fixed in https://github.com/you-dont-need/You-Dont-Need-GUI/pull/20
@vasanthaganeshk please comment if you disagree :)
