### ISSUE TITLE
Moving a file

### ISSUE THREAD

**Issue by MauJFernandezUVR** [you-dont-need/You-Dont-Need-GUI#11]
Please, when moving a file to a directory always use a trailing slash at the end of the folder to avoid mistakes:

`mv readme.txt documents/`

[For this reason](http://unix.stackexchange.com/a/50533)

**Comment by MauJFernandezUVR** [comment]
Here's the PR: https://github.com/you-dont-need/You-Dont-Need-GUI/pull/12

**Comment by stevemao** [comment]
Sounds reasonable.

**Comment by Berkmann18** [comment]
Shouldn't this be closed since #12 got merged?

**Comment by cht8687** [comment]
@Berkmann18 yes. thanks for that.
