### ISSUE TITLE
can't `stat -x`

### ISSUE THREAD

**Issue by aeosynth** [you-dont-need/You-Dont-Need-GUI#15]
```
$ stat -x README.md
stat: invalid option -- 'x'
Try 'stat --help' for more information.
$ stat --version
stat (GNU coreutils) 8.25
```

Arch Linux

**Comment by stevemao** [comment]
Summoning Linux users @cht8687 @mitermayer :)

**Comment by cht8687** [comment]
I think in Linux it is %x

**Comment by cht8687** [comment]
But %x is for checking the last access for example:  `stat -c "%x" README.md`
so, we can actually directly call: `stat README.md`

**Comment by aeosynth** [comment]
why don't you just split them, mac `stat`, linux `du`

**Comment by aeosynth** [comment]
a comment that `stat -x` is only for macOS

**Comment by stevemao** [comment]
https://github.com/you-dont-need/You-Dont-Need-GUI/pull/22

**Comment by ashleyharvey** [comment]
Vote to close!
