### ISSUE TITLE
Add shell indicator

### ISSUE THREAD

**Issue by Jogai** [you-dont-need/You-Dont-Need-GUI#27]
Some do work in the git bash on windows. Maybe its nice to have an indicator for that?

**Comment by stevemao** [comment]
Thanks for opening this @Jogai. Maintainers here are either Mac or Linux users. PR welcome :)

**Comment by ashleyharvey** [comment]
@stevemao and this one..

**Comment by stevemao** [comment]
@ashleyharvey BTW, I have invited you to this repo so that you can also manage it 😄

**Comment by ashleyharvey** [comment]
> @ashleyharvey BTW, I have invited you to this repo so that you can also manage it 😄

Thank you!
