### ISSUE TITLE
Find command do not work on Ubuntu

### ISSUE THREAD

**Issue by georgy7** [you-dont-need/You-Dont-Need-GUI#28]
This command has extra plus.

```
find . -mtime +5 | wc -l
668944   # Wrong.

find . -mtime 5 | wc -l
1565     # It looks valid.
```

**Comment by Aversiste** [comment]
Here is the difference between the two:

* `find . -mtime 5`: find files with a modification time of **exactly** five days ;
* `find . -mtime +5`: find files with a modification time of **at least** five days.

Chances are you have a lot of old files around.

**Comment by stevemao** [comment]
Just send us a PR please.

**Comment by georgy7** [comment]
@Aversiste That is true, my bad. What I wanted was `find . -mtime -5`.
