### ISSUE TITLE
“Create a new file” suggests two totally different commands

### ISSUE THREAD

**Issue by notpushkin** [you-dont-need/You-Dont-Need-GUI#29]
There are two alternative commands suggested:

```bash
touch 'new file'
# or
> 'new file'
```

While both commands are OK for creating files, the ultimate meaning of them is different: e. g. if the file already exists, the former would just update the access timestamp on it, while the later will also remove its contents. It is probably worth noting, especially since this guide is aimed at the beginners.

**Comment by stevemao** [comment]
I agree. PR welcome!

**Comment by Berkmann18** [comment]
@notpushkin Have you started working on the PR?
If not I'll do it.

**Comment by stevemao** [comment]
@Berkmann18 Feel free to submit your PR :)
