### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by celestiallake** [you-dont-need/You-Dont-Need-GUI#31]
"You don't need GUI" just sounds too loud. You've pretty much described the basic *nix commands which are used by the majority of people anyway. Go hardcore, push for Vim and Emacs as the editors, ncmpcpp as the music player, tmux as the way to get some viewport layout...

Well, what about tiling WMs like i3 or AwesomeWM?

**Comment by anh072** [comment]
so true. I dont find the repo useful

**Comment by Berkmann18** [comment]
> which are used by the majority of people anyway

I wish I would agree but studies I've read (+ personal experience) suggest we ("CLI rockers") are in not the majority, mind showing your sources?

**Comment by tomhoad** [comment]
The title is misleading in that it presents a pretty solid argument **for** using a GUI.

**Comment by mutexdeveloper** [comment]
It isn't meant to literally mean "never use a GUI".

For example: [You don't need JavaScript](https://github.com/you-dont-need/You-Dont-Need-JavaScript)
This doesn't mean "Never use anything but css in web development".

**Comment by sicaboy** [comment]
Ditto, "You don't really need it" != "Never use it"
