### ISSUE TITLE
Should we use less directly, instead of being piped from cat?

### ISSUE THREAD

**Issue by altbdoor** [you-dont-need/You-Dont-Need-GUI#44]
In reference to the section "view content of a file", the recommendation to view a larger file is:

```sh
# if the file is too big to fit on one page, you can send it to a 'pager' (less) which shows you one page at a time.
$ cat apps/settings.py | less
```

Wouldn't `less apps/settings.py` be sufficient?

**Comment by ashleyharvey** [comment]
> In reference to the section "view content of a file", the recommendation to view a larger file is:
> 
> ```shell
> # if the file is too big to fit on one page, you can send it to a 'pager' (less) which shows you one page at a time.
> $ cat apps/settings.py | less
> ```
> 
> Wouldn't `less apps/settings.py` be sufficient?

Yes! Not just sufficient, but preferable.
