### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by AtticusLv** [you-dont-need/You-Dont-Need-GUI#59]
Thx for this repository. Do u have plan to support other languages?
I can help with Chinese version😊

**Comment by cht8687** [comment]
Hi @AtticusLv 
seems there is already a PR for this https://github.com/you-dont-need/You-Dont-Need-GUI/pull/60. But it would be great to have the Chinese version under this same repo.

**Comment by cht8687** [comment]
https://github.com/you-dont-need/You-Dont-Need-GUI/pull/60
