### ISSUE TITLE
I'm using GUI to view the page "you dont need GUI"

### ISSUE THREAD

**Issue by Domado** [you-dont-need/You-Dont-Need-GUI#74]
What a funny thing!

**Comment by kenteroshima** [comment]
How about using terminal browsers like <a href="https://github.com/tats/w3m">w3m</a>?

**Comment by mutexdeveloper** [comment]
![1676243367](https://user-images.githubusercontent.com/74791818/218342887-3a01d456-712d-4b2b-bec9-eb86e8468a3e.png)
Ha, Amateur!

**Comment by sicaboy** [comment]
LOL Nice one!
