### ISSUE TITLE
that's why people complains that linux sucks

### ISSUE THREAD

**Issue by NotteShock** [you-dont-need/You-Dont-Need-GUI#76]
I know that some commands are useful and faster than GUI, but why the need of an terminal and a long command just for copy/paste an file? No wonder why Linux still has a low market share as a desktop OS

**Comment by UndefinedCpp** [comment]
Exactly. I hardly use these commands except on a linux console. I really wonder why they'll suggest using commands when GUI actually make daily things easier.

**Comment by mutexdeveloper** [comment]
If you don't know how to use the terminal. Use the GUI.
Simple?

**Comment by sicaboy** [comment]
> If you don't know how to use the terminal. Use the GUI.
> Simple?

Sometimes you don't have that option. Especially you / your employer are using a server version of Linux distribution

**Comment by mutexdeveloper** [comment]
> > If you don't know how to use the terminal. Use the GUI.
> > Simple?
> 
> Sometimes you don't have that option. Especially you / your employer are using a server version of Linux distribution

If you're managing linux servers, Yes.
They're referencing linux on a desktop.

**Comment by sicaboy** [comment]
> > > If you don't know how to use the terminal. Use the GUI.
> > > Simple?
> > 
> > 
> > Sometimes you don't have that option. Especially you / your employer are using a server version of Linux distribution
> 
> If you're managing linux servers, Yes. They're referencing linux on a desktop.

Same thing. Even you are using a a Desktop GUI, for example, when you want to check connection, would you rather do a quick `ping` or `nc -vz` or search and pay for a suitable pretty software?

**Comment by mutexdeveloper** [comment]
> > > > ...
> > > > ...
> > > 
> > > 
> > > ...
> > 
> > 
> > If you're managing linux servers, Yes. They're referencing linux on a desktop.
> 
> Same thing. Even you are using a Desktop GUI, for example, when you want to check connection, would you rather do a quick `ping` / `nc -vz` or search and pay for a suitable pretty software?
You don't need to pay to check your network connection, Just try make a connection? You don't NEED a terminal for that.
I don't doubt terminal is quicker. but if you don't want to learn to use it, then you don't have to.

**Comment by sicaboy** [comment]
> > > > > ...
> > > > > ...
> > > > 
> > > > 
> > > > ...
> > > 
> > > 
> > > If you're managing linux servers, Yes. They're referencing linux on a desktop.
> > 
> > 
> > Same thing. Even you are using a Desktop GUI, for example, when you want to check connection, would you rather do a quick `ping` / `nc -vz` or search and pay for a suitable pretty software?
> 
> You don't need to pay to check your network connection, Just try make a connection? You don't NEED a terminal for that. I don't doubt terminal is quicker. but if you don't want to learn to use it, then you don't have to.

Just a simple question, do you have an alternative for the following command?

```
$ nc -vz 1.1.1.1 53
Connection to 1.1.1.1 port 53 [tcp/domain] succeeded!
```

**Comment by mutexdeveloper** [comment]
> > > > > > ...
> > > > > > ...
> > > > > 
> > > > > 
> > > > > ...
> > > > 
> > > > 
> > > > If you're managing linux servers, Yes. They're referencing linux on a desktop.
> > > 
> > > 
> > > Same thing. Even you are using a Desktop GUI, for example, when you want to check connection, would you rather do a quick `ping` / `nc -vz` or search and pay for a suitable pretty software?
> > 
> > 
> > You don't need to pay to check your network connection, Just try make a connection? You don't NEED a terminal for that. I don't doubt terminal is quicker. but if you don't want to learn to use it, then you don't have to.
> 
> Just a simple question, do you have an alternative for the following command?
> 
> ```
> $ nc -vz 1.1.1.1 53
> Connection to 1.1.1.1 port 53 [tcp/domain] succeeded!
> ```

You're missing my point.
I'm saying if you don't know how to use the terminal and you are fine using the UI. Use the UI and don't complain.
There are going to be things you can only do in a terminal. But if you don't need to use it, then you don't need to learn to use the terminal.
