### ISSUE TITLE
Simplify "run command on every file in a directory"

### ISSUE THREAD

**Issue by mutexdeveloper** [you-dont-need/You-Dont-Need-GUI#79]
Am I wrong or could 
https://github.com/you-dont-need/You-Dont-Need-GUI/blob/886ca5e930cfa152f18946617edc3e327e840e78/readme.md?plain=1#L578
be simplified to 
```sh
$ echo *
```

**Comment by flzara** [comment]
I think you're missing the point here. 
`echo $FILE` is just an example of a command. It's harmless and may be replaced by your own command. 

Or maybe you're just trolling just like what you're doing in #76 🧌

**Comment by mutexdeveloper** [comment]
> I think you're missing the point here. 
> `echo $FILE` is just an example of a command. It's harmless and may be replaced by your own command. 
> 
> Or maybe you're just trolling just like what you're doing in #76 🧌
> 

They're the exact same command? You can just replace echo in both and it would function the same, Neither is harmless.

I'm not trolling here or in #76. Not sure what part of #76 you're confused by.
